-
  title: '【預購專區】NIKE ROMALEOS II 高階舉重鞋*橘'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/3e27c22674b0724019e4f1421488c862'
  description: '自2012年發售至今，NIKE R2一直都是舉重鞋市場中的當紅炸子雞，不管是專業選手或一般休閒玩家都給予極高的評價，5年來無鞋可出其右。

可惜的是，NIKE在今年推出了R2的後繼鞋款R3，就目前消費者的回饋來看，R3簡直可以說是一場「災難」，鞋的重量不均、平衡感欠佳，更慘的是被幹到爆的品管，地雷瑕疵鞋滿街跑，有人鞋舌一拉就斷、有人鞋底一踩就爆。

但在商言商，不管R3再怎麼爛、評價再怎麼差，NIKE也不可能搬石頭砸自己腳，所以R2不管再怎麼神、再怎麼受歡迎，它終究是一款即將要走入歷史的鞋子......

也因為這樣，現在市場上出現了一股「回頭搶R2」的風潮，就在您猶豫的同時，廠商的庫存也越來越少！請不要錯過最後這次收藏R2的機會！

※下標前請讀一讀※

一、這是預購，不是現貨

從美國商家出貨、坐飛機、過海關，至少也要14~20天的時間，如果沒有耐心可以等待，請不要下標，謝謝。

二、這是直購，不是連線代購

5850這個價錢就是包含運費、關稅等雜費，水肥哥不會像連線代購業者那樣外面標一個價，實際下標是另一個價錢，嫌貴就不要買，謝謝。

三、棄標者一定給負評、黑名單

本次預購是採「貨到付款」方式，所以您不用擔心被騙錢什麼之類的，但是如果您中途棄標，會給水肥哥造成很大的困擾，下標前請先確定荷包有錢，謝謝。

四、臨時換色不另行通知

就像文章內所述的，R2即將絕版，斷號、斷碼非常嚴重，如果您原本預訂的顏色沒有尺寸，水肥哥就會買其他顏色來替補，最有可能的替補是橘色，如果你對橘色厭惡至極，請不要下標，謝謝。

最後提醒大家一下，只要好好保養、使用，一雙舉重鞋可以穿7年、8年絕對不是問題，買了這一雙，練到死都不用再換了！

不要再考慮！不要再猶豫！現在就下標吧！

PS：尺寸部份請比照NIKE籃球鞋，籃球鞋穿多大、舉重鞋就買多大，沒有穿過NIKE的請自行找家運動用品店試穿，3Q。'
  price: 5850
  remain: 10
  specs_attributes:
  -
    name: '6'
    quantity: 1
  -
    name: '6.5'
    quantity: 0
  -
    name: '7'
    quantity: 2
  -
    name: '7.5'
    quantity: 2
  -
    name: '8'
    quantity: 2
  -
    name: '8.5'
    quantity: 2
  -
    name: '9'
    quantity: 0
  -
    name: '9.5'
    quantity: 3
  -
    name: '10'
    quantity: 4
  -
    name: '10.5'
    quantity: 4
  -
    name: '11'
    quantity: 2
  -
    name: '11.5'
    quantity: 3
  -
    name: '12'
    quantity: 2
  -
    name: '12.5'
    quantity: 1
-
  title: '超級訓練】臥推輔助彈弓'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/71376b463cfc4f0288921fa343017a42'
  description: '<span>無壓力一級彈弓(藍/粉紅) - 臥推不足100公斤者適用
初版二級彈弓(紅/迷彩) - 臥推100~140公斤者適用
野豬三級彈弓(黃) - 臥推140~180公斤者適用
瘋狗四級彈弓(黑) - 臥推180+公斤者適用

※彈弓的主要用處除了方便加重、做更多下之外，使用彈弓還有一個好處是它會強制你在臥推的過程中背部必須出力、避免手肘外開過多，這種推法不只較符合正確前推的動作機制，也能保護你的肩膀、手肘，降低受傷的機會。&nbsp;一般在建議上，我會建議槓鈴臥推不足100公斤者，請挑選最軟的無壓力彈弓，超過100公斤者，挑選原始的初版彈弓，超過140公斤者，挑選黃色的野豬彈弓，超過180公斤者，再考慮材質最厚的瘋狗彈弓。之所以這樣，是因為彈弓的機制就像臥推裝備賽事專用的「臥推衣」，離心階段需要背出力將之撐開，如果對應的力量不夠強，你可能會連將槓鈴放到胸口都有難度。尺寸方面，一般男生請挑選2XL為主，身高超過180公分或手臂很粗的巨巨，再考慮3XL，只有女孩子或身高不足170公分的瘦小男性，我才會推薦你挑選XL或以下的尺寸。※</span>'
  price: 1690
  remain: 10
  specs_attributes:
  -
    name: '藍色/粉紅無壓力彈弓XL'
    quantity: 1
  -
    name: '藍色/粉紅無壓力彈弓2XL'
    quantity: 2
  -
    name: '迷彩/紅色初版彈弓XL'
    quantity: 2
-
  title: '【超級訓練】黑色動態彈性「三級防護」專業健身護膝'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/c46a3a7cd23c92ed2371c560ce1e3dbb'
  description: '動態彈性「三級防護」專業健身護膝！厚度高達7mm！共有三種顏色可挑選！

●動態彈性「三級防護」vs強力硬派「四級防護」，我該選哪種護膝？●

－強力硬派護膝材質較硬，深蹲時儲存的彈性位能比較大，所以理論上能給予配戴者更好的回饋，但也因為如此，有些動作，如前蹲、屁股到底的全蹲等，會因為強力硬派護膝太硬的關係，在運動時會經常覺得「卡卡」的，反而會影響到動作的平衡。

所以該戴哪種護膝比較好呢？水肥哥個人的建議是，如果你在健身房除了「深蹲」之外，還會從事很多動態活動，比如跑、跳、甩壺鈴等，那就買動態彈性「三級防護」的護膝，尤其是從事「舉重」或「Crossfit」的玩家特別推薦；相反地，如果你戴護膝的唯一目的只有深蹲，而且是「蹲一半」的健力式深蹲，本身有一顆追求「最大重量」的心，那我就會建議您買強力硬派「四級防護」護膝！

●護膝尺寸怎麼挑？●

－挑選護膝的尺寸有兩個重點，第一是拿捲尺量你膝蓋中間處正上方約10公分的位置，第二個是量小腿肚最粗的地方，基本上要兩個地方都符合上面的尺寸表，才能夠順利套上。一般穿不上護膝，多半是方法不對，水肥哥會建議大家在練腿時裡面穿件壓力褲或緊身褲，因為這些褲子的材質很光滑，摩擦力會比人體的皮膚小，穿護膝會好穿很多。

●護膝穿法教學影片●

https://www.youtube.com/watch?v=bjntlr-wcMM

※護膝是成對販賣，請不要再問了※'
  price: 2190
  remain: 10
  specs_attributes:
  -
    name: 'S'
    quantity: 1
  -
    name: 'M'
    quantity: 0
  -
    name: 'L'
    quantity: 2
  -
    name: 'XL'
    quantity: 0
  -
    name: '2XL'
    quantity: 1
  -
    name: '3XL'
    quantity: 3
-
  title: '【超級訓練】強力專業健身護肘'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/419e7055d13d11a852d66f56b56ca247'
  description: '強力專業健身護肘，厚度高達5mm，適合臥推、肩推、雙槓等運動中，通過專業大力士比賽測試，絕對能提供給您的關節與肌肉最頂級的防護！

※護肘是成對販賣，請不要再問了※'
  price: 1780
  remain: 10
  specs_attributes:
  -
    name: '藍色S'
    quantity: 1
  -
    name: '藍色M'
    quantity: 1
  -
    name: '藍色L'
    quantity: 3
  -
    name: '藍色XL'
    quantity: 0
  -
    name: '藍色2XL'
    quantity: 1
  -
    name: '藍色3XL'
    quantity: 1
  -
    name: '黑色S'
    quantity: 1
  -
    name: '黑色M'
    quantity: 0
  -
    name: '黑色L'
    quantity: 0
  -
    name: '黑色XL'
    quantity: 3
  -
    name: '黑色2XL'
    quantity: 2
  -
    name: '黑色3XL'
    quantity: 2
-
  title: '【超級訓練】粉紅動態彈性「三級防護」專業健身護膝'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/b2e91489072c4ac2a0a988ea0f1dc69b'
  description: '動態彈性「三級防護」專業健身護膝！厚度高達7mm！共有三種顏色可挑選！

●動態彈性「三級防護」vs強力硬派「四級防護」，我該選哪種護膝？●

－強力硬派護膝材質較硬，深蹲時儲存的彈性位能比較大，所以理論上能給予配戴者更好的回饋，但也因為如此，有些動作，如前蹲、屁股到底的全蹲等，會因為強力硬派護膝太硬的關係，在運動時會經常覺得「卡卡」的，反而會影響到動作的平衡。

所以該戴哪種護膝比較好呢？水肥哥個人的建議是，如果你在健身房除了「深蹲」之外，還會從事很多動態活動，比如跑、跳、甩壺鈴等，那就買動態彈性「三級防護」的護膝，尤其是從事「舉重」或「Crossfit」的玩家特別推薦；相反地，如果你戴護膝的唯一目的只有深蹲，而且是「蹲一半」的健力式深蹲，本身有一顆追求「最大重量」的心，那我就會建議您買強力硬派「四級防護」護膝！

●護膝尺寸怎麼挑？●

－挑選護膝的尺寸有兩個重點，第一是拿捲尺量你膝蓋中間處正上方約10公分的位置，第二個是量小腿肚最粗的地方，基本上要兩個地方都符合上面的尺寸表，才能夠順利套上。一般穿不上護膝，多半是方法不對，水肥哥會建議大家在練腿時裡面穿件壓力褲或緊身褲，因為這些褲子的材質很光滑，摩擦力會比人體的皮膚小，穿護膝會好穿很多。

●護膝穿法教學影片●

https://www.youtube.com/watch?v=bjntlr-wcMM

※護膝是成對販賣，請不要再問了※'
  price: 1600
  remain: 10
  specs_attributes:
  -
    name: 'S'
    quantity: 1
  -
    name: 'M'
    quantity: 0
  -
    name: 'L'
    quantity: 2
  -
    name: 'XL'
    quantity: 0
  -
    name: '2XL'
    quantity: 1
  -
    name: '3XL'
    quantity: 3
-
  title: '【原價3650】愛迪達健力舉重鞋3.0－太空黑『男鞋』'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/07f1cb84c20ff492f1ccd3d9ccb19c4d'
  description: '全新品，門市原價3650，愛迪達健力舉重鞋3.0－太空黑『男鞋』！
US7=25cm
US12.5=30.5cm
US14=32cm'
  price: 2800
  remain: 10
  specs_attributes:
  -
    name: '7'
    quantity: 0
  -
    name: '12.5'
    quantity: 1
  -
    name: '14'
    quantity: 2
  -
    name: '9.5=27.5cm'
    quantity: 1
  -
    name: '11=29cm'
    quantity: 0
-
  title: '【泰坦】二級防護「猛牛」快扣健力／健身泛用腰帶'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/eca3f5a7aaa9354e5ba81c79a46654f2'
  description: '二級防護「猛牛」健力／健身泛用腰帶適合

※剛想投入健力運動，不知道自己適合什麼腰帶的朋友
※骨架較小、體重較輕，戴太厚腰帶經常會卡到肋骨非常疼痛的朋友
※在健身房除了深蹲、臥推、硬舉之外，會長時間配戴腰帶的朋友
※對健力沒興趣，但仍有腰帶需求的朋友

二級防護「猛牛」快扣健力／健身泛用腰帶雖然皮質較軟，但對比市面上一些便宜的腰帶用厚紙板、塑膠布濫竽充數，「猛牛」的用料可是真材實料，完美的車工和剪裁提供您最佳的運動體驗，很多輕量級的選手都會捨棄硬幫幫的高價腰帶選擇配戴「猛牛」，這就足以證明其品質是有口皆碑的！

同時，泰坦／強者世界還提供了目前台灣業界唯一的「終生保固」，腰帶只要是在合理使用範圍內（被火燒毀、泡水發臭、被剪刀剪斷這種就不算嚕）出現斷裂、解體的狀況，只要支付運費就可以免費獲得一條一模一樣的全新二級防護「猛牛」快扣健力／健身泛用腰帶！

別懷疑！我們就是對自己的產品這麼有信心！'
  price: 2890
  remain: 10
  specs_attributes:
  -
    name: '黑S（腰圍26~29）'
    quantity: 0
  -
    name: '黑M（腰圍30~33）'
    quantity: 1
  -
    name: '藍M（腰圍30~33）'
    quantity: 2
  -
    name: '藍L（腰圍34~37）'
    quantity: 1
  -
    name: '紅M（腰圍30~33）'
    quantity: 0
  -
    name: '紅L（腰圍34~37）'
    quantity: 1
-
  title: '【ROGUE】男版「健力咖」合身短T'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/9f4f25db2dbd4dd6136c7543e11a2945'
  description: '「挑戰極限，化鐵成鋼，我不是在健身，我是練健力。」

羅格「ROGUE」8月新款T-SHIRT，今天下單、明天取貨，現貨販售，數量有限，賣完不會再進喔。

※衣服材質：50％聚酯纖維+25％棉+25%人造絲※
－美國製造！品質保證！'
  price: 1080
  remain: 10
  specs_attributes:
  -
    name: 'S'
    quantity: 1
  -
    name: 'M'
    quantity: 0
  -
    name: 'L'
    quantity: 2
  -
    name: 'XL'
    quantity: 0
  -
    name: '2XL'
    quantity: 1
-
  title: '【強者世界】「熊老大」簡易護腕快速拉力帶'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/71f1ce18912234bbb8a65ce1dffa3c5a'
  description: '「熊老大」簡易護腕快速拉力帶，是「強者世界」自行生產的第二代快速拉力帶，「熊老大」採用的是目前歐美最新產品的全新切割款式，材質也較一代更耐用，「熊老大」同時也根據上一代用戶的回饋建議，提供了簡易的護腕功能，唯一不變的就是同樣超值的價格，對於一般健身房的休閒族群來說，可以說是最俗又大碗的快速版拉力帶選擇！'
  price: 550
  remain: 10
-
  title: '【原價3650】愛迪達健力舉重鞋3.0－薰衣草紫『女鞋』'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/968bbf91ae54766844f55f7caa213814'
  description: '全新品，門市原價3650，愛迪達健力舉重鞋3.0－薰衣草紫『女鞋』！
US7.5=24.5cm
US8=25cm
US8.5=25.5cm'
  price: 2800
  remain: 6
-
  title: '【超級訓練】MB1強力「四級防護」專業健身護膝(限量版)'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/19038b2774e75fd99dfe5e156c13c524'
  description: 'MB1強力「四級防護」專業健身護膝！厚度高達7mm！因為是限量發售故進貨價格比較貴一些，敬請見諒！

※護膝是成對販賣，請不要再問了※'
  price: 3250
  remain: 8
-
  title: '【ROGUE】男版基本款短T*美國國旗'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/82a4277a4c02b6d774160b8a782cf2cb'
  description: '
ROGUE，羅格，亦有「俠盜」之意，光是這個名字就已經說明了這個品牌所希望呈現的精神－叛逆不羈、嚮往自由！

羅格成立於2007年，創辦人Bill Henniger一開始只是希望建立一個匯整家庭健身房器材的平台，但後來他發現客戶買東西時經常必須透過好幾個廠商才能買齊，造成出貨時間表不一與許多不必要的運費，最後他決定自己下來做。

幾年下來，羅格慢慢靠著消費者累積口碑成為美國國內家用健身器材的第一品牌，後來更被「CROSSFIT」選為比賽指定贊助廠商之一，即使今天公司的規模已經不可同日而語，Bill Henniger仍堅持創業之初「美國製造」的理想，提供消費者俗又大碗的最優質產品！

穿膩了UA、NIKE、ADIDAS？連逛個大賣場都會撞衫？那就別再問了，快點加入ROGUE的行列吧！

※衣服材質：50％聚酯纖維+50％棉※
－美國製造！品質保證！'
  price: 1080
  remain: 3
  specs_attributes:
  -
    name: 'S'
    quantity: 1
  -
    name: 'M'
    quantity: 5
  -
    name: 'L'
    quantity: 2
  -
    name: 'XL'
    quantity: 0
  -
    name: '2XL'
    quantity: 1
-
  title: '【團購取件專用】＃熱情粉紅＃三級防護「長角」快扣競技款健力腰帶'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/7f6bab12467cd376ced8b0e199e0bbd6'
  description: '此賣場暫時只提供給去年團購選擇「自取」的朋友下單專用，請路過的大哥大姊們不要下單喔！'
  price: 4050
  remain: 10
-
  title: '【ROGUE】男版「戰術系統」短T'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/49d7f0b69b7c1bf84b3e34be00b18ed2'
  description: 'ROGUE，羅格，亦有「俠盜」之意，光是這個名字就已經說明了這個品牌所希望呈現的精神－叛逆不羈、嚮往自由！

羅格成立於2007年，創辦人Bill Henniger一開始只是希望建立一個匯整家庭健身房器材的平台，但後來他發現客戶買東西時經常必須透過好幾個廠商才能買齊，造成出貨時間表不一與許多不必要的運費，最後他決定自己下來做。

幾年下來，羅格慢慢靠著消費者累積口碑成為美國國內家用健身器材的第一品牌，後來更被「CROSSFIT」選為比賽指定贊助廠商之一，即使今天公司的規模已經不可同日而語，Bill Henniger仍堅持創業之初「美國製造」的理想，提供消費者俗又大碗的最優質產品！

穿膩了UA、NIKE、ADIDAS？連逛個大賣場都會撞衫？那就別再問了，快點加入ROGUE的行列吧！

※衣服材質：50％聚酯纖維+50％棉※
－這件「戰術系統」短T，是ROGUE特別與美國知名的防身術專家Tony Blauer合作開發，美國許多軍人、警察、特種部隊，都曾是他的學生！只剩一件，不要錯過喔！'
  price: 1080
  remain: 2
-
  title: '超級訓練四級護膝XS黑'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/f483e5ad2772c424d8e416d00517e9bd'
  description: '超級訓練四級護膝XS黑'
  price: 2450
  remain: 1
-
  title: '【ROGUE】男版「大力士」合身短T'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/69272c0848328edc0a599c7d1e904b4f'
  description: '「氣拔山河，力大無窮，我不是在健身，我是大力士。」

羅格「ROGUE」8月新款T-SHIRT，今天下單、明天取貨，現貨販售，數量有限，賣完不會再進喔。

※衣服材質：50％聚酯纖維+25％棉+25%人造絲※
－美國製造！品質保證！'
  price: 1080
  remain: 2
  specs_attributes:
  -
    name: 'S'
    quantity: 1
  -
    name: 'M'
    quantity: 3
  -
    name: 'L'
    quantity: 1
  -
    name: 'XL'
    quantity: 1
  -
    name: '2XL'
    quantity: 1
-
  title: '【SBD】冬季限定款「四級防護」彈性／剛硬護腕'
  image_url: 'https://cfshopeetw-a.akamaihd.net/file/6e6c856877ba2571d39c138bb395d35e'
  description: 'SBD，來自英國的頂級健力護具廠商，也是目前國際健力協會「無裝備」賽事最大的贊助廠，承襲歐洲血統的優良傳統，SBD的產品一向以高雅簡約的設計、一絲不茍的品質著稱，如果是以「無裝備」比賽為目標的健力同好，選擇SBD就對啦！'
  price: 1750
  remain: 5
